DWAPlannerROS:
  acc_lim_x: 1.33
  acc_lim_trans: 1.33
  acc_lim_y: 0
  acc_lim_theta: 10
  max_vel_trans: 0.5
  min_vel_trans: 0.05
  max_vel_x: 0.5
  min_vel_x: 0
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 1.5
  min_vel_theta: 0.3

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  sim_time: 4.0
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  controller_frequency: 10

  path_distance_bias: 40
  goal_distance_bias: 20
  occdist_scale: 0.02
  publish_cost_grid: true

  oscillation_reset_dist: 0.05

  prune_plan: true  