local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.05
  transform_tolerance: 1.0
  map_type: costmap

  inflation_layer:
    cost_scaling_factor: 2.5
    inflation_radius: 0.75